name: 某科学的弹幕委员会
pygments: true
markdown: rdiscount

# configuration required for some pages
domain: bbcallen.github.com
title: 某科学的弹幕委员会
author: bbcallen
email: bbcallen@gmail.com

# global config
my_path:
  down_biliplayer: "/downloads/app/biliplayer.apk"
